#ifndef __CallDirectorCacheDefs_h__
#define __CallDirectorCacheDefs_h__

enum CallDirectorCacheConstants {
   MAX_IP_SIZE = 100,
   MAX_MAC_SIZE = 12,
   MAX_NAME_SIZE = 65,
   MAX_RESOURCE_NAME_SIZE = MAX_NAME_SIZE,
   MAX_CARRIER_NAME = MAX_NAME_SIZE,
   MAX_FILE_NAME = 150,
   MAX_PHONE_NUMBER = 25,
   MAX_URI = 256,

   MAX_CARRIERS = 100,
   MAX_APPLICATIONS = 100,
   MAX_DNISS = 100,

   MAX_SUBRACKS = 2,
   MAX_MEDIA_GATEWAYS_SUBRACK = 2,
   MAX_SPEECH_SERVERS_SUBRACK = 7,
   MAX_CALL_DIRECTORS_SUBRACK = 1,

   MAX_LINE_CARDS_MEDIA_GATEWAY = 7,
   MAX_SPAN_LINE_CARD = 4,
   MAX_TRUNK_GROUPS_LINE_CARD = MAX_SPAN_LINE_CARD,
   MAX_CHANNELS_MANAGERS_LINE_CARD = 2,
   MAX_SPANS_TRUNK_GROUP = MAX_SPAN_LINE_CARD,
   MAX_CHANNELS_SPAN = 24,

   MAX_LINE_CARDS_SUBRACK = MAX_LINE_CARDS_MEDIA_GATEWAY * MAX_MEDIA_GATEWAYS_SUBRACK,
   MAX_SPAN_MEDIA_GATEWAY = MAX_SPAN_LINE_CARD * MAX_LINE_CARDS_MEDIA_GATEWAY,
   MAX_SPAN_SUBRACK = MAX_SPAN_LINE_CARD * MAX_LINE_CARDS_SUBRACK,

   MAX_MEDIA_GATEWAYS_RACK = MAX_MEDIA_GATEWAYS_SUBRACK * MAX_SUBRACKS,
   MAX_SPEECH_SERVERS_RACK = MAX_SPEECH_SERVERS_SUBRACK * MAX_SUBRACKS,
   MAX_CALL_DIRECTORS_RACK = MAX_CALL_DIRECTORS_SUBRACK * MAX_SUBRACKS,
   MAX_LINE_CARDS_RACK = MAX_LINE_CARDS_MEDIA_GATEWAY * MAX_MEDIA_GATEWAYS_RACK,
   MAX_TRUNK_GROUPS_RACK = MAX_TRUNK_GROUPS_LINE_CARD * MAX_LINE_CARDS_RACK,
   MAX_SPAN_RACK = MAX_SPAN_LINE_CARD * MAX_LINE_CARDS_RACK,

   MAX_TRUNK_GROUPS_APPLICATION = MAX_TRUNK_GROUPS_RACK
};

enum LineCardType {
   LC_AUDIOCODES
};

enum TrunkGroupConst {
   TG_INBOUND =  0x1,
   TG_OUTBOUND = 0x2,
   TG_LOCAL =    0x10,
   TG_LONGDISTANCE = 0x20,
   TG_LOCALTOLL = 0x40,
   TG_TOLLFREE = 0x80,
   TG_BAD = 0xFFFF
};

enum DChannelConfigConst {
   DCH_PRIMARY =  0,
   DCH_BACKUP = 1,
   DCH_NFAS =    2
};

#endif // __CallDirectorCacheDefs_h__
